---
- name: Install git
  become: true
  apt:
    name: git
    state: present
    update_cache: yes

- name: Check out the book source code to home
  git:
    repo: 'https://github.com/seeker89/chaos-engineering-in-action.git'
    dest: /home/chaos/src
