---
- name: Install apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_repositories }}"

- name: Preinstall packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages_to_install }}"

- name: Check out the book source code to home
  git:
    repo: 'https://github.com/seeker89/chaos-engineering-in-action.git'
    dest: /home/chaos/src

- name: Make all the examples
  shell: make
  args:
    chdir: /home/chaos/src
