---
- name: Install apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_repositories }}"

- name: Preinstall packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages_to_install }}"

- name: Check out the book source code to home
  git:
    repo: 'https://github.com/seeker89/chaos-engineering-in-action.git'
    dest: /home/chaos/src

- name: Make all the examples
  shell: make
  args:
    chdir: /home/chaos/src

- name: Install kind
  shell: |
    curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
    chmod +x ./kind
    sudo mv ./kind /usr/bin/kind
    exit 0
  args:
    creates: /usr/bin/kind

- name: Install pumba
  shell: |
    curl -Lo ./pumba "https://github.com/alexei-led/pumba/releases/download/0.6.8/pumba_linux_amd64"
    chmod +x ./pumba
    sudo mv ./pumba /usr/bin/pumba
    exit 0
  args:
    creates: /usr/bin/pumba
